version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
  node: circleci/node@3.0.0
  cypress: cypress-io/cypress@1.26.0
jobs:
  test:
    working_directory: ~/scalprum
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: install-deps
          command: yarn
      - run:
          name: build-packages
          command: yarn build
      - run:
          name: test
          command: yarn test
      - run:
          name: lint
          command: yarn lint
      - codecov/upload:
          file: coverage/*.json
          token: c6e9b194-44be-4a27-8a27-b16e2beba0d6
      - persist_to_workspace:
          root: ~/scalprum
          paths:
              - "*"


workflows:
  version: 2
  build:
    jobs:
      - test
      - cypress/run:
          requires:
            - test
          yarn: true
          start: yarn start:test
          wait-on: 'http://localhost:8123'
          executor: cypress/base-14
          post-steps:
            - store_test_results:
                path: cypress/results
            - store_artifacts:
                path: cypress/artifacts
