version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
  node: circleci/node@3.0.0
jobs:
  test:
    working_directory: ~/scalprum
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@7'
      - run:
          name: install-deps
          command: npm i
      - run:
          name: build-packages
          command: npm run build
      - run:
          name: test
          command: npm run test
      - run:
          name: lint
          command: npm run lint
      - codecov/upload:
          file: coverage/*.json
          token: aa1b6b4d-79a1-49f6-bcb2-d6069134a772
      - persist_to_workspace:
          root: ~/scalprum
          paths:
              - "*"

workflows:
  version: 2
  build:
    jobs:
      - test
